# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr=np.array([25,25,22,44])


# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([
    [1,2,3,4,5,6,7,8],
    [9,7,5,4,3,2,1,3]])


# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[
    [1,2,3,4,5,6,7,8,9],
    [9,8,7,6,5,4,3,2,1],
    [3,3,4,6,4,8,9,0,5]
]])
print(arr)
print(arr2)
print(arr3)

[25 25 22 44]
[[1 2 3 4 5 6 7 8]
 [9 7 5 4 3 2 1 3]]
[[[1 2 3 4 5 6 7 8 9]
  [9 8 7 6 5 4 3 2 1]
  [3 3 4 6 4 8 9 0 5]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr.shape,arr.ndim,arr.size,print(type(arr))


<class 'numpy.ndarray'>


((4,), 1, 4, None)

In [4]:
# Attributes of 2-dimensional array
arr2.shape,arr2.ndim,arr2.size,print(type(arr2))

<class 'numpy.ndarray'>


((2, 8), 2, 16, None)

In [5]:
# Attributes of 3-dimensional array
arr3.shape,arr3.ndim,arr3.size,print(type(arr3))

<class 'numpy.ndarray'>


((1, 3, 9), 3, 27, None)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
Name = ['Zain', 'Rawa', 'nick', 'juli']
Age = arr[:4]
list_of_tuples = list(zip(Name, Age))
df = pd.DataFrame(list_of_tuples,
                  columns=['Name', 'Age'])

print(df)


      


   Name  Age
0  Zain   25
1  Rawa   25
2  nick   22
3  juli   44


In [7]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10, 2))

print(ones_arr)
print("Shape:", ones_arr.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (10, 2)


In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zerosArr=np.zeros((7,2,3))
print(zerosArr)
print("shape:",zerosArr.shape)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
shape: (7, 2, 3)


In [9]:
# Create an array within a range of 0 and 100 with step 3
arr4 = np.arange(0, 100, 3)
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr5 = np.random.randint(0, 10, size=(7, 2))
arr5


array([[6, 2],
       [6, 6],
       [0, 2],
       [0, 9],
       [7, 2],
       [1, 7],
       [6, 7]], dtype=int32)

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr6=np.random.rand(3,5)
arr6


array([[0.27571527, 0.19305467, 0.50868244, 0.73854138, 0.60213861],
       [0.78298544, 0.71691546, 0.54087895, 0.11583635, 0.87432208],
       [0.61709804, 0.72024728, 0.81773183, 0.66126587, 0.85468289]])

In [12]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
arr7=np.random.randint(0,10,size=(4,6))
arr7


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

## Run the cell above again, what happens?
* The numbers in the array remain exactly the same.



## Are the numbers in the array different or the same? Why do think this is?
* Reasoning:
This happens because we initialized the Pseudo-Random Number Generator (PRNG) with a fixed seed (np.random.seed(42)). In computer science, "random" numbers are actually calculated using deterministic algorithms. By setting a constant seed, we ensure that the algorithm starts at the same point every time the cell is executed, resulting in reproducible outputs. This is a critical practice in Machine Learning to ensure that experiments can be verified and compared under identical stochastic conditions.


In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr8=np.random.randint(1,10,size=(3,7))
arr8


# Find the unique numbers in the array you just created
unique_num=np.unique(arr8)
print(unique_num)



[1 2 3 4 5 7 9]


In [14]:
# Find the 0'th index of the latest array you created
arr8[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [15]:
# Get the first 2 rows of latest array you created
arr8[ :2]


array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
arr8[:2,:2]


array([[9, 1],
       [5, 3]], dtype=int32)

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr9=np.random.randint(0,10,size=(3,5))
arr10=np.ones((3,5))


In [18]:
# Add the two arrays together
result=np.add(arr9,arr10)
result


array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
arrrrry=np.ones((5,3))
arrrrry


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Try add the array of ones and the other most recent array together
result=np.add(arrrrry,arr10)
result

## When you try the last cell, it produces an error. Why do think this is?
* The error happens due to a Shape Mismatch. In NumPy, element-wise operations like addition require the arrays to have compatible dimensions.

Array 1 is (5, 3) (5 rows, 3 columns).

Array 2 is (3, 5) (3 rows, 5 columns).

Since the rows and columns don't align, NumPy's Broadcasting rules cannot determine how to pair the individual elements, resulting in a ValueError

## How would you fix it?
* We can fix this by ensuring the shapes match before adding. There are two ways:

Transposing: Use .T to flip the rows and columns of the second array so it becomes (5, 3).

Reshaping: Use .reshape(5, 3) if the total number of elements allows it

In [20]:
# Create another array of ones of shape (3, 5)
Ones_arr=np.ones((3,5))
Ones_arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Subtract the new array of ones from the other most recent array
result=np.subtract(arr9,Ones_arr)
result

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [22]:
# Multiply the ones array with the latest array
result = arr9 * Ones_arr
result


array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [23]:
# Take the latest array to the power of 2 using '**'
result**2



array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [24]:
# Do the same thing with np.square()
result=np.square(arr9)
result


array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [25]:
# Find the mean of the latest array using np.mean()
np.mean(arr9)


np.float64(3.8666666666666667)

In [26]:
# Find the maximum of the latest array using np.max()
np.max(arr9)


np.int32(9)

In [27]:
# Find the minimum of the latest array using np.min()
np.min(arr9)

np.int32(0)

In [28]:
# Find the standard deviation of the latest array
np.std(arr9)

np.float64(2.578543947441829)

In [29]:
# Find the variance of the latest array
np.var(arr9)


np.float64(6.648888888888889)

In [30]:
# Reshape the latest array to (3, 5, 1)
arr9.reshape(3,5,1)
arr9


array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]], dtype=int32)

In [31]:
# Transpose the latest array
arrT=arr9.T
arrT


array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]], dtype=int32)

## لاWhat does the transpose do?
* Transposing an array (matrix) flips it over its main diagonal. Mathematically, it switches the row and column indices of every element: an element at position $(i, j)$ moves to $(j, i)$.

In [32]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1=np.random.randint(0,10,size=(3,3))
arr2=np.random.randint(0,10,size=(3,2))
print("arr1=",arr1)
print("arr2=",arr2)

arr1= [[9 1 9]
 [3 7 6]
 [8 7 4]]
arr2= [[1 4]
 [7 9]
 [8 8]]


In [33]:
# Perform a dot product on the two newest arrays you created
arr3=np.dot(arr1,arr2)
arr3


array([[ 88, 117],
       [100, 123],
       [ 89, 127]], dtype=int32)

In [34]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1=np.random.randint(0,10,size=(4,3))
arr2=np.random.randint(0,10,size=(4,3))

# Perform a dot product on the two newest arrays you created
arr3=np.dot(arr1,arr2)
arr3

## It doesn't work. How would you fix it?
* The operation np.dot(arr1, arr2) fails with a ValueError because the shapes are incompatible for matrix multiplication.The Problem: Both arrays have a shape of $(4, 3)$. According to the rules of Linear Algebra, the number of columns in the first matrix must equal the number of rows in the second matrix. Here, $9 \neq 5$.The Fix: We must Transpose the second array to align the inner dimensions. By using arr2.T, its shape becomes $(3, 4)$.The Result: The operation now becomes $(4, 3) \cdot (3, 4)$, which is mathematically valid and results in a $(4, 4)$ output matrix

In [35]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3=arr1.T
arr4=np.dot(arr2,arr3)
arr4


array([[ 24,  16,  22,   8],
       [102, 114, 123,  60],
       [ 96, 106, 114,  58],
       [  8,  63,  56,   7]], dtype=int32)

## Notice how performing a transpose allows the dot product to happen.

## Why is this?
* According to the rules of Matrix Multiplication, the number of columns in the first matrix must match the number of rows in the second matrix.
When we have two arrays of the same shape, e.g., $(3, 5)$ and $(3, 5)$, they are incompatible for a dot product. By transposing the second array, its shape becomes $(5, 3)$. This aligns the inner dimensions $(3, 5) \cdot (5, 3)$, satisfying the mathematical requirement and resulting in a $(3, 3)$ output matrix

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [36]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(42)
arr1=np.random.randint(0,11,size=(5,9))
arr2=np.random.randint(0,11,size=(5,9))

In [37]:
# Compare the two arrays with '>'
arr1>arr2


array([[False,  True,  True, False, False,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False,  True,  True, False],
       [False, False,  True, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False, False],
       [False, False,  True, False, False, False, False,  True, False]])

## What happens when you compare the arrays with `>`?
* When using the > operator on two NumPy arrays of the same shape, an element-wise comparison is performed.

Mechanism: NumPy compares each element in the first array with the corresponding element (at the same index) in the second array.

Output: The result is a Boolean Array of the same shape (5, 9).

Values: Each position in the resulting array contains True if the element in arr1 is strictly greater than the element in arr2, and False otherwise.

This is a fundamental concept in NumPy called Vectorization, which allows us to perform logical operations across entire datasets without using slow Python loops.

In [38]:
# Compare the two arrays with '>='
arr1>=arr2


array([[False,  True,  True, False, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True, False, False,  True,  True],
       [ True, False,  True,  True,  True,  True,  True, False, False],
       [False, False,  True, False, False,  True, False,  True, False]])

In [39]:
# Find which elements of the first array are greater than 
greater_than_7 = arr1[arr1 > 7]
print(greater_than_7)
indices = np.where(arr1 > 7)
print(indices)


[10  9 10 10  9  8 10 10  9  8  8]
(array([0, 0, 1, 1, 2, 3, 3, 3, 3, 3, 4]), array([2, 6, 0, 1, 7, 0, 2, 3, 4, 8, 5]))


In [40]:
# Which parts of each array are equal? (try using '==')
equal_num = (arr1 == arr2)

total_matches = np.sum(equal_num)

   
matching_values = arr1[equal_num]

print(f"Number of equal elements: {total_matches}")
print(f"The actual equal values: {matching_values}")

Number of equal elements: 7
The actual equal values: [6 7 5 5 1 9 8]


In [41]:
# Sort one of the arrays you just created in ascending order
arr1_sorted = np.sort(arr1)
arr1_sorted

array([[ 2,  3,  4,  6,  6,  6,  7,  9, 10],
       [ 2,  3,  4,  5,  7,  7,  7, 10, 10],
       [ 0,  1,  1,  4,  4,  5,  5,  7,  9],
       [ 0,  2,  3,  6,  8,  8,  9, 10, 10],
       [ 1,  2,  2,  3,  4,  4,  6,  6,  8]], dtype=int32)

In [42]:
# Sort the indexes of one of the arrays you just created
sorted_indices = np.argsort(arr1)
sorted_indices


array([[7, 1, 4, 0, 5, 8, 3, 6, 2],
       [7, 4, 3, 8, 5, 6, 2, 0, 1],
       [6, 1, 4, 0, 5, 3, 8, 2, 7],
       [1, 5, 7, 6, 0, 8, 4, 3, 2],
       [7, 0, 2, 8, 4, 1, 6, 3, 5]])

In [43]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(arr1)
print(max_index)

2


In [44]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(arr1)
print(min_index)

24


In [45]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices_row = np.argmax(arr1, axis=1)
max_indices_row

array([2, 0, 7, 2, 5])

In [46]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_row = np.argmin(arr1, axis=0)
min_indices_row

array([4, 3, 4, 1, 2, 3, 2, 4, 4])

In [47]:
# Create an array of normally distributed random numbers
normal_array = np.random.normal(loc=0, scale=1, size=(5, 9))
normal_array


array([[ 1.03099952,  0.93128012, -0.83921752, -0.30921238,  0.33126343,
         0.97554513, -0.47917424, -0.18565898, -1.10633497],
       [-1.19620662,  0.81252582,  1.35624003, -0.07201012,  1.0035329 ,
         0.36163603, -0.64511975,  0.36139561,  1.53803657],
       [-0.03582604,  1.56464366, -2.6197451 ,  0.8219025 ,  0.08704707,
        -0.29900735,  0.09176078, -1.98756891, -0.21967189],
       [ 0.35711257,  1.47789404, -0.51827022, -0.8084936 , -0.50175704,
         0.91540212,  0.32875111, -0.5297602 ,  0.51326743],
       [ 0.09707755,  0.96864499, -0.70205309, -0.32766215, -0.39210815,
        -1.46351495,  0.29612028,  0.26105527,  0.00511346]])

In [48]:
# Create an array with 10 evenly spaced numbers between 1 and 100
linspace_arr = np.linspace(1, 100, 10)
linspace_arr


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.